version: "3.9"
services:
  python:
    build: 
      context: python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    ports:
      - 4000:4000

  crawler-bot:
    build:
      context: crawler-bot
      dockerfile: Dockerfile
    volumes:
      - ./crawler-bot:/app
      - ./python/output:/app/output
