version: "3.9"
services:
  react:
    build: 
      context: node
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./node:/app
    ports:
      - 3000:3000

  python:
    build: 
      context: python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app

  crawler-bot:
    build:
      content: crawler-bot
      dockerfile: Dockerfile
    volumes:
      - ./crawler-bot:/app
