version: "3.9"
services:
  node:
    build: 
      context: node
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./node:/app
    ports:
      - 3000:3000

  python:
    build: 
      context: python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    ports:
      - 4000:4000

  crawler-bot:
    build:
      context: crawler-bot
      dockerfile: Dockerfile
    volumes:
      - ./crawler-bot:/app
